// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk3EAfgeD0J3uhp-xpicUUlUO8FvNe110',
    appId: '1:895812912916:web:3b3271d7a47b2d682ce401',
    messagingSenderId: '895812912916',
    projectId: 'rainify-4d64e',
    authDomain: 'rainify-4d64e.firebaseapp.com',
    storageBucket: 'rainify-4d64e.firebasestorage.app',
    measurementId: 'G-B8W883WD0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDvjtOL7gC1VKG-DrZq27bTiL0dkh0ycY',
    appId: '1:895812912916:android:64afdb9e2e734b852ce401',
    messagingSenderId: '895812912916',
    projectId: 'rainify-4d64e',
    storageBucket: 'rainify-4d64e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrGI0J60JOyamWsktDG1l4bf4AoC2wfFk',
    appId: '1:895812912916:ios:83b8b5ffcf02d7612ce401',
    messagingSenderId: '895812912916',
    projectId: 'rainify-4d64e',
    storageBucket: 'rainify-4d64e.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrGI0J60JOyamWsktDG1l4bf4AoC2wfFk',
    appId: '1:895812912916:ios:83b8b5ffcf02d7612ce401',
    messagingSenderId: '895812912916',
    projectId: 'rainify-4d64e',
    storageBucket: 'rainify-4d64e.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk3EAfgeD0J3uhp-xpicUUlUO8FvNe110',
    appId: '1:895812912916:web:a5ab51b8833e9f3a2ce401',
    messagingSenderId: '895812912916',
    projectId: 'rainify-4d64e',
    authDomain: 'rainify-4d64e.firebaseapp.com',
    storageBucket: 'rainify-4d64e.firebasestorage.app',
    measurementId: 'G-1EJNG0508K',
  );
}
